import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/waitlist/Header'
import Footer from '@/components/waitlist/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GridApe',
  description: 'Generated by GridApe',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`bg-[#FFFAE9] ${inter.className}`}>
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
        <Header />
        {children}
        {/* </ThemeProvider> */}
        <Footer />
      </body>
    </html>
  )
}
